### ISSUE TITLE
Custom LogManager

### ISSUE THREAD

**Issue by 304NotModified** [jpdillingham/xLogger#12]
Nice lib! 

Maybe it's also nice to create a custom LogManager? Saves some boilerplate code for the end user.

**Comment by jpdillingham** [comment]
Thanks for the note!

I considered a LogManager extension class, however LogManager is sealed.

Now that I'm thinking about it more I think I could create extension methods LogManager.GetxLogger() and LogManager.GetCurrentClassxLogger().  Thanks for the suggestion!

**Comment by jpdillingham** [comment]
Not sure what I was thinking but you can't add extension methods to static types.  I ended up making a LogManager wrapper; it contains GetxLogger() and GetCurrentClassxLogger(), but that's it. 

[Commit here](https://github.com/jpdillingham/xLogger/commit/df9b57ab342bccb025e480628ddd0403e7438fa3) (forgot to reference in commit message)
